### ISSUE TITLE
Library not in Maven Central

### ISSUE THREAD

**Issue by upachler** [CleverTap/apns-http2#9]
The library is not released to Maven Central or any other publicly available repository, which makes it much harder to use.

If needed, I could assist in such a release.

**Comment by judepereira** [comment]
We'll be adding this to Maven Central soon. I'll keep this open until it's released.

**Comment by icecreamhead** [comment]
Any update on this?

**Comment by judepereira** [comment]
Hey @icecreamhead, not yet. I've not got around to using this due to lack of time. I should be able to have this done soon though.

**Comment by rajibm2005** [comment]
I'm doing a PoC for APNS with CleverTap's apns-http2 library. It looks promising so far. Could you please add to maven central ? 

Also, I found exception handling can be improved in the code. 

if (cachedJWTToken == null || System.currentTimeMillis() - lastJWTTokenTS > 55 * 60 * 1000) {
                try {
                    lastJWTTokenTS = System.currentTimeMillis();
                    cachedJWTToken = JWT.getToken(teamID, keyID, apnsAuthKey);
                } catch (InvalidKepSpecException | NoSuchAlgorithmException | SignatureException | InvalidKeyException e) {
                    return null;
}

Can we throw proper exception here, instead of returning null so that we know what exactly went wrong (e,g premature EOF etc) ? 

Please let me know your thoughts on this.

**Comment by Eiarzate1** [comment]
@rajibm2005 What did you end up doing? Did you end up using apns-http2 for your actual product?

**Comment by EasonFeng5870** [comment]
pls hurry up man

**Comment by judepereira** [comment]
It's now available:
<dependency>
    <groupId>com.clevertap.apns</groupId>
    <artifactId>apns-http2</artifactId>
    <version>1.0.2</version>
</dependency>
